### PR TITLE
add raw-output option for json output

### PR DESCRIPTION
**Pull request by adonisgarciac**
When you run this action with json: true, the output doesn't work properly because double quotes are escaped in the content of array:

code:

```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true

      - uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.WEBHOOK_URL_DEV }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_DEV }}
          data: '{ "modified_files": ${{ steps.changed-files.outputs.all_changed_files }} }'

```

output

```
    data: { "modified_files": [\".github/workflows/github-dev-webhook.yml\",\"file.yml\"] }
```

Error:

```
parse error: Invalid numeric literal at line 1, column 23
```

If I check the code where json is parsed:

```
$ echo hello | jq -R 'split("|") | @json'| sed -r 's/^"|"$//g' | tr -s /
[\"hello\"]
```

With this change, the output will be:

```
$ echo hello | jq -r -R 'split("|") | @json'| sed -r 's/^"|"$//g' | tr -s /
["hello"]
```

### CODE REVIEW

**Comment by jackton1** [comment]
@adonisgarciac Thanks for submitting the fix. I’ll suggest we make this an optional behavior via an input I.e `json-raw: true`. Since this breaks the usage of the action with `fromJSON`.

See: https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson

**Review by jackton1 — CHANGES_REQUESTED** [review]
Add optional input to return raw JSON output from `jq`. You’ll need to abstract the behaviour into a function that can be used with pipe

**Comment by adonisgarciac** [comment]
> Add optional input to return raw JSON output from `jq`. You’ll need to abstract the behaviour into a function that can be used with pipe

Thank you @jackton1. You are totally right! Let me know if there are some mistakes in the last changes that I have done with jq_raw_input as a variable.

**Comment by jackton1** [comment]
@all-contributors please add @adonisgarciac for code, docs

**Review by jackton1 — APPROVED** [review]

**Pull request merged**
